In [1]:
import numpy as np


class Perceptron(object):

    def __init__(self, input_size, lr=0.2, epochs=4):
        self.W = np.array([0.3, -0.2])
        self.epochs = epochs
        self.lr = lr

    # Step activation function
    def activation_fn(self, x):
        return 1 if x >= 0 else 0

    # Prediction function
    def predict(self, x, theta):
        z = self.W.T.dot(x) - theta
        z = round(z, 2)
        a = self.activation_fn(z)
        return a

    # Learning function
    def fit(self, X, d, theta, count):

        for _ in range(self.epochs):

            print("Epoch:", count)
            count = count + 1

            for i in range(d.shape[0]):

                x = X[i]

                print("Input:", x, "\tWeight:", self.W)

                # Predict output
                y = self.predict(x, theta)

                # Calculate error
                e = d[i] - y

                # Update weights
                self.W = self.W + self.lr * e * x

                print("Predicted:", y, "\tDesired:", d[i])
                print("Error:", e)
                print("Updated Weight:", self.W)
                print()


# Main program
if __name__ == '__main__':

    # Input values for AND gate
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

    # Desired output
    d = np.array([0, 0, 0, 1])

    # Create Perceptron object
    perceptron = Perceptron(input_size=2)

    # Threshold
    theta = 0.4

    # Starting epoch count
    count = 1

    # Train the perceptron
    perceptron.fit(X, d, theta, count)

    # Print final learned weights
    print("Final Learned Weights:")
    print(perceptron.W)

Epoch: 1
Input: [0 0] 	Weight: [ 0.3 -0.2]
Predicted: 0 	Desired: 0
Error: 0
Updated Weight: [ 0.3 -0.2]

Input: [0 1] 	Weight: [ 0.3 -0.2]
Predicted: 0 	Desired: 0
Error: 0
Updated Weight: [ 0.3 -0.2]

Input: [1 0] 	Weight: [ 0.3 -0.2]
Predicted: 0 	Desired: 0
Error: 0
Updated Weight: [ 0.3 -0.2]

Input: [1 1] 	Weight: [ 0.3 -0.2]
Predicted: 0 	Desired: 1
Error: 1
Updated Weight: [0.5 0. ]

Epoch: 2
Input: [0 0] 	Weight: [0.5 0. ]
Predicted: 0 	Desired: 0
Error: 0
Updated Weight: [0.5 0. ]

Input: [0 1] 	Weight: [0.5 0. ]
Predicted: 0 	Desired: 0
Error: 0
Updated Weight: [0.5 0. ]

Input: [1 0] 	Weight: [0.5 0. ]
Predicted: 1 	Desired: 0
Error: -1
Updated Weight: [0.3 0. ]

Input: [1 1] 	Weight: [0.3 0. ]
Predicted: 0 	Desired: 1
Error: 1
Updated Weight: [0.5 0.2]

Epoch: 3
Input: [0 0] 	Weight: [0.5 0.2]
Predicted: 0 	Desired: 0
Error: 0
Updated Weight: [0.5 0.2]

Input: [0 1] 	Weight: [0.5 0.2]
Predicted: 0 	Desired: 0
Error: 0
Updated Weight: [0.5 0.2]

Input: [1 0] 	Weight: [0.5 0

In [9]:
import numpy as np


# ==========================================================
# Sigmoid activation function
# ==========================================================
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# ==========================================================
# Sigmoid derivative
# ==========================================================
def sigmoid_derivative(x):
    return x * (1 - x)


# ==========================================================
# Check whether error exists
# ==========================================================
def checkError(predicted_output):
    expected_output = np.array([
        [0],
        [1],
        [1],
        [0]
    ])

    for i, j in zip(expected_output, predicted_output):

        if abs(i[0] - j[0]) > 0.01:
            return True

    return False


# ==========================================================
# XOR input data
# ==========================================================
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=float)


# ==========================================================
# XOR expected output
# ==========================================================
expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=float)


# ==========================================================
# Learning rate
# ==========================================================
lr = 0.1


# ==========================================================
# Epoch counter
# ==========================================================
epoch = 0


# ==========================================================
# Number of neurons
# ==========================================================
inputLayerNeurons = 2
hiddenLayerNeurons = 2
outputLayerNeurons = 1


# ==========================================================
# Initial hidden layer weights
# ==========================================================
hidden_weights = np.array([
    [0.1, 0.2],
    [0.3, 0.4]
], dtype=float)


# ==========================================================
# Initial output layer weights
# ==========================================================
output_weights = np.array([
    [0.5],
    [0.6]
], dtype=float)


# ==========================================================
# Initial hidden layer biases
# ==========================================================
hidden_bias = np.array([
    [0.1, 0.1]
], dtype=float)


# ==========================================================
# Initial output layer bias
# ==========================================================
output_bias = np.array([
    [0.1]
], dtype=float)


# ==========================================================
# Display initial values
# ==========================================================
print("==========================================")
print("INITIAL VALUES")
print("==========================================")

print("\nInitial hidden weights:")
print(hidden_weights)

print("\nInitial hidden bias:")
print(hidden_bias)

print("\nInitial output weights:")
print(output_weights)

print("\nInitial output bias:")
print(output_bias)


# ==========================================================
# Initial predicted output
# ==========================================================
predicted_output = np.array([
    [0],
    [0],
    [0],
    [0]
], dtype=float)


# ==========================================================
# Maximum number of epochs
# ==========================================================
max_epochs = 100000


# ==========================================================
# TRAINING
# ==========================================================
while checkError(predicted_output) and epoch < max_epochs:

    epoch += 1

    # ------------------------------------------------------
    # Forward Propagation
    # ------------------------------------------------------

    # Hidden layer activation
    hidden_layer_activation = np.dot(
        inputs,
        hidden_weights
    )

    # Add hidden layer bias
    hidden_layer_activation += hidden_bias

    # Hidden layer output
    hidden_layer_output = sigmoid(
        hidden_layer_activation
    )


    # ------------------------------------------------------
    # Output layer activation
    # ------------------------------------------------------

    output_layer_activation = np.dot(
        hidden_layer_output,
        output_weights
    )

    # Add output layer bias
    output_layer_activation += output_bias

    # Final prediction
    predicted_output = sigmoid(
        output_layer_activation
    )


    # ------------------------------------------------------
    # Backward Propagation
    # ------------------------------------------------------

    # Calculate error
    error = expected_output - predicted_output


    # ------------------------------------------------------
    # Output layer gradient
    # ------------------------------------------------------

    d_predicted_output = (
        error *
        sigmoid_derivative(predicted_output)
    )


    # ------------------------------------------------------
    # Hidden layer error
    # ------------------------------------------------------

    error_hidden_layer = d_predicted_output.dot(
        output_weights.T
    )


    # ------------------------------------------------------
    # Hidden layer gradient
    # ------------------------------------------------------

    d_hidden_layer = (
        error_hidden_layer *
        sigmoid_derivative(hidden_layer_output)
    )


    # ------------------------------------------------------
    # Update output layer weights
    # ------------------------------------------------------

    output_weights += (
        hidden_layer_output.T.dot(
            d_predicted_output
        ) * lr
    )


    # ------------------------------------------------------
    # Update output layer bias
    # ------------------------------------------------------

    output_bias += (
        np.sum(
            d_predicted_output,
            axis=0,
            keepdims=True
        ) * lr
    )


    # ------------------------------------------------------
    # Update hidden layer weights
    # ------------------------------------------------------

    hidden_weights += (
        inputs.T.dot(
            d_hidden_layer
        ) * lr
    )


    # ------------------------------------------------------
    # Update hidden layer bias
    # ------------------------------------------------------

    hidden_bias += (
        np.sum(
            d_hidden_layer,
            axis=0,
            keepdims=True
        ) * lr
    )


# ==========================================================
# FINAL FORWARD PROPAGATION
# ==========================================================
# This is important because the final weights have been
# updated after the last training iteration.

hidden_layer_activation = np.dot(
    inputs,
    hidden_weights
)

hidden_layer_activation += hidden_bias

hidden_layer_output = sigmoid(
    hidden_layer_activation
)


output_layer_activation = np.dot(
    hidden_layer_output,
    output_weights
)

output_layer_activation += output_bias

predicted_output = sigmoid(
    output_layer_activation
)


# ==========================================================
# FINAL RESULTS
# ==========================================================

print("\n==========================================")
print("FINAL RESULTS")
print("==========================================")


print("\nFinal hidden weights:")
print(hidden_weights)


print("\nFinal hidden bias:")
print(hidden_bias)


print("\nFinal output weights:")
print(output_weights)


print("\nFinal output bias:")
print(output_bias)


# ==========================================================
# Final neural network output
# ==========================================================

print("\n==========================================")
print("NEURAL NETWORK OUTPUT")
print("==========================================")

print("\nInput    Expected    Predicted")

for i in range(len(inputs)):

    print(
        inputs[i],
        "     ",
        int(expected_output[i][0]),
        "       ",
        round(predicted_output[i][0], 6)
    )


# ==========================================================
# Number of epochs
# ==========================================================

print("\n==========================================")
print("TRAINING INFORMATION")
print("==========================================")

print("\nNumber of epochs:")
print(epoch)


# ==========================================================
# Training status
# ==========================================================

if epoch >= max_epochs:

    print(
        "\nTraining stopped because "
        "maximum epochs were reached."
    )

else:

    print(
        "\nTraining completed successfully."
    )

INITIAL VALUES

Initial hidden weights:
[[0.1 0.2]
 [0.3 0.4]]

Initial hidden bias:
[[0.1 0.1]]

Initial output weights:
[[0.5]
 [0.6]]

Initial output bias:
[[0.1]]

FINAL RESULTS

Final hidden weights:
[[4.83919748 6.68388607]
 [4.84025489 6.68811193]]

Final hidden bias:
[[-7.42366525 -3.00178764]]

Final output weights:
[[-10.98767602]
 [ 10.2970431 ]]

Final output bias:
[[-4.7980466]]

NEURAL NETWORK OUTPUT

Input    Expected    Predicted
[0. 0.]       0         0.013163
[0. 1.]       1         0.988746
[1. 0.]       1         0.988743
[1. 1.]       0         0.01158

TRAINING INFORMATION

Number of epochs:
100000

Training stopped because maximum epochs were reached.
